name: Django CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:   # MySQL service
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: supersecretroot
          MYSQL_DATABASE: messaging_db
          MYSQL_USER: messaging_user
          MYSQL_PASSWORD: messaging_pass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      DB_NAME: messaging_db
      DB_USER: messaging_user
      DB_PASSWORD: messaging_pass
      DB_HOST: db   # must match the service name
      DB_PORT: 3306
      SECRET_KEY: testsecretkey

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r messaging_app/requirements.txt

      - name: Run migrations
        run: |
          cd messaging_app
          python manage.py migrate --noinput

      - name: Run tests
        run: |
          cd messaging_app
          python manage.py test --verbosity=2 --keepdb

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: messaging_app/test-results.xml
